# ===================================================================
# netty
# ===================================================================
netty:
  server:
    config:
      port: 9999
server:
  port: 8082
