# ===================================================================
# netty
# ===================================================================
netty:
  server:
    config:
      port: 9999
server:
  port: 8082
# ===================================================================
# mybatis
# ===================================================================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.beidou.server.entity
mapper:
  mappers: com.beidou.server.common.IBaseMapper
  not-empty: false
  identity: MYSQL
