# ===================================================================
# netty
# ===================================================================
netty:
  client:
    config:
      host: "127.0.0.1"
      port: 9999

server:
  port: 10001
