server:
  #端口
  port: 7000
  #访问路径
  servlet:
    context-path: /

spring:
  #应用名
  application:
    name: gateway
  redis:
    #host: localhost
    host: "120.76.196.44"
    port: 6379
    password:
    timeout: 0
    expire: 1800
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@register1:8001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@register2:8002/eureka/
      defaultZone: http://admin:admin@register1:8001/eureka/,http://admin:admin@register2:8002/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    statusPageUrlPath: /actuator/info
    prefer-ip-address: true

#路由配置
zuul:
  ignoredServices: '*'
  #HTTP请求头不进行转发
  sensitive-headers: Cookie,Set-Cookie,Authorization
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 600000
    max-per-route-connections: 20
    max-total-connections: 200

  routes:
    api-1:
      path: /api/v1/logger/**
      serviceId: logger
    api-2:
      path: /api/v1/monitor/**
      serviceId: monitor
    api-3:
      path: /api/v1/car/**
      serviceId: car

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml

info:
  app:
    name: "@project.name@"  #从pom.xml中获取,pom.xml中需build中加入插件spring-boot-maven-plugin
    description: "@project.description@"
    version: "@project.version@"
    author: "许b"

mybatis:
  typeAliasesPackage: com.beidou.gateway.entity
  mapperLocations: classpath:mapper/*.xml

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 2500
