#端口
server:
  port: 8003

spring:
  #应用名
  application:
    name: monitor
      #（加入密码认证）
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${session.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://admin:admin@register1:8001/eureka/,http://admin:admin@register2:8002/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    statusPageUrlPath: /actuator/info
      #（加入密码认证）
    metadata-map:
      user.name: admin
      user.password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml

info:
  app:
    name: "@project.name@"  #从pom.xml中获取,pom.xml中需build中加入插件spring-boot-maven-plugin
    description: "@project.description@"
    version: "@project.version@"
    author: "许b"

